site_name: Maverickid's Notes
theme:
  name: material
  logo: assets/head.jpg
  favicon: assets/head.jpg
nav:
  - Home: "index.md"
  - "课程笔记":
    - CS61A: Courses/CS61A/index.md
    - ADS:
      - "Week1": Courses/ADS/week1.md
      - "Week2": Courses/ADS/week2.md
      - "Week3": Courses/ADS/week3.md
      - "Week4": Courses/ADS/week4.md
      - "Week5": Courses/ADS/week5.md
      - "Week6": Courses/ADS/week6.md
      - "Week7": Courses/ADS/week7.md
      - "Week8": Courses/ADS/week8.md
      - "midTerm Review": Courses/ADS/midtermReview.md
    - 计组: 
          - "intro": Courses/Computer_Organization/index.md
          - "Chapter2": Courses/Computer_Organization/Chapter2.md
          - "Chapter3": Courses/Computer_Organization/Chapter3.md
          - "Exception": Courses/Computer_Organization/Exception.md
    - DB: 
          - "intro": Courses/DataBaseSystem/index.md
          - "Lecture5": Courses/DataBaseSystem/Lecture5.md
    - C++: Courses/C++/Memory Model in C++.md
  - Other:
      - "About Transformer": theory_paper/aboutTransformer/About Transformer.md
markdown_extensions:
  - admonition #MkDocs 警告框
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
extra_css:
  - css/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
