site_name: Welcome to some CS courses' notes
theme:
  name: material
  logo: assets/head.jpg
  favicon: assets/head.jpg
nav:
  - Home: "index.md"
  - "课程笔记":
    - CS61A: CS61A/index.md
markdown_extensions:
  - admonition #MkDocs 警告框
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
extra_css:
  - css/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
